name: Java CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  EC2_USER: ec2-user
  EC2_HOST: 57.181.37.197
  SRC_PATH: build/libs/*.jar
  DEST_PATH: /home/ec2-user/StudentManagement.jar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run tests
        run: ./gradlew test

      - name: Build application (bootJar)
        run: ./gradlew bootJar

      - name: Check built jar
        run: ls -al build/libs

      - name: Create private key file from secret
        run: |
          printf '%s\n' "${{ secrets.AWS_EC2_PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: SCP copy application jar to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i private_key build/libs/*.jar ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:${{ env.DEST_PATH }}

      - name: SSH Application Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.EC2_HOST }}
          username: ${{ env.EC2_USER }}
          key_path: private_key
          script: |
            sudo yum update -y
            if sudo systemctl is-active --quiet StudentManagement; then
              sudo systemctl restart StudentManagement
            else
              sudo systemctl start StudentManagement
            fi

      - name: Cleanup private key
        if: always()
        run: |
         rm -f private_key
